// Express
import express from "express";
import http from "http";
import bodyParser from "body-parser";
import path from "path";

// Swagger
import swaggerUi from "swagger-ui-express";
import yaml from "yamljs";

// Logging
import Logger from "./Logger";

// Properties
import properties from "../properties.js";

// Security
import cors from "cors";
import helmet from "helmet";

// Controllers
import SecurityController from "../controllers/SecurityController";

// Start Import Controllers

// Database
import Database_PruebaSka_db from "./Database_PruebaSka_db.js";

// Controllers
import EmpresasController from "../controllers/PruebaSka_db/EmpresasController";
import UserController from "../controllers/PruebaSka_db/UserController";
import CategoriaMenuController from "../controllers/PruebaSka_db/CategoriaMenuController";
import ConfigController from "../controllers/PruebaSka_db/ConfigController";
import ItemMenuController from "../controllers/PruebaSka_db/ItemMenuController";
import ItemOrdenController from "../controllers/PruebaSka_db/ItemOrdenController";
import MediaController from "../controllers/PruebaSka_db/MediaController";
import MenuController from "../controllers/PruebaSka_db/MenuController";
import MesasController from "../controllers/PruebaSka_db/MesasController";
import OrdenesController from "../controllers/PruebaSka_db/OrdenesController";
import TiposMediaController from "../controllers/PruebaSka_db/TiposMediaController";
import UserEmpresaController from "../controllers/PruebaSka_db/UserEmpresaController";

// End Import Controllers


class Server {
  constructor() {
    this.app = express();
  }

  /**
   * Start the server
   * @returns {Promise<void>}
   */
  async init() {
    Logger.info(
      "\r\n\r\n-----------------------------------\r\n\r\nStarting MyCRM \r\nGenerated by\r\n\r\n   _____ _          __  __      _     _           \r\n  / ____| |        / _|/ _|    | |   | |          \r\n | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __ \r\n  \\___ \\| |/ / _` |  _|  _/ _ \\| |/ _` |/ _ \\ '__|\r\n  ____) |   < (_| | | | || (_) | | (_| |  __/ |   \r\n |_____/|_|\\_\\__,_|_| |_| \\___/|_|\\__,_|\\___|_|   \r\n\r\nFor more documentation please visit https://skaffolder.com/#/documentation\r\n\r\n-----------------------------------\r\n\r\n"
    );

    // Start Init Database
		Database_PruebaSka_db.init();
 // End Init Database

    // Add parser
    this.app.use(bodyParser.json());
    this.app.use(bodyParser.urlencoded({ extended: true }));
    this.app.use(Logger.expressMiddleware);

    // Securitiy
    this.app.use(helmet());
    this.app.use(cors());

    // Swagger
    const swaggerDocument = yaml.load("./swagger.yaml");
    this.app.use(
      "/api/docs",
      swaggerUi.serve,
      swaggerUi.setup(swaggerDocument)
    );

    // Redirect frontend
    this.app.use("*", (req, res, next) => {
      if (req.originalUrl) {
        let url = req.originalUrl;
        if (!url.startsWith("/api/") && url.indexOf(".") == -1) {
          res
            .status(200)
            .sendFile(
              path.resolve(__dirname + "//..//..//client//dist//index.html")
            );
        } else {
          next();
        }
      } else {
        next();
      }
    });
    
    // Start App Server
    const server = http.Server(this.app);
    this.app.use(express.static(properties.publicPath));

    await server.listen(properties.port);
    Logger.info("Server started on port " + properties.port);
    Logger.info(
      "Swagger docs at http://localhost:" + properties.port + "/api/docs"
    );

    // Import controllers
    const router = express.Router();
    SecurityController.init(router);

    // Start Init Controllers
		EmpresasController.init(router);
		UserController.init(router);
		CategoriaMenuController.init(router);
		ConfigController.init(router);
		ItemMenuController.init(router);
		ItemOrdenController.init(router);
		MediaController.init(router);
		MenuController.init(router);
		MesasController.init(router);
		OrdenesController.init(router);
		TiposMediaController.init(router);
		UserEmpresaController.init(router);
		 // End Init Controllers

    this.app.use("/", router);
  }
}

export default new Server();
